#!/usr/bin/env python
"""The one Studio step: generate the harvest snippet, then merge what Studio printed back.

    py tools/assets/harvest.py --emit [--all]     # write tools/assets/harvest.luau from Assets.json
    py tools/assets/harvest.py                    # merge [HARVEST] lines from the Windows clipboard
    py tools/assets/harvest.py --file out.txt     # ...or from a saved copy of the Output window

Why a Studio step at all: Open Cloud returns one Model asset id per upload, but the template
files need the MeshId and TextureID (Image asset) that Roblox creates *inside* that model, plus
the MeshPart's size and its offset from the glTF origin. Only `InsertService:LoadAsset` in
Studio can reveal those. harvest.luau (generated, ids embedded, never edited by hand) loads
each asset, prints one `[HARVEST] {json}` line per asset and destroys what it loaded; this
script parses those lines and writes them into Assets.json. Missing lines leave entries
untouched and are listed.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import assets_config as cfg  # noqa: E402

LUAU_PATH = os.path.join(HERE, "harvest.luau")
MARKER = "[HARVEST] "

LUAU_TEMPLATE = """\
-- Generated by `py tools/assets/harvest.py --emit` from src/shared/Config/Assets.json. Do not edit.
--
-- 1. Open the place in Roblox Studio (Edit mode, not Play). View > Command Bar, View > Output.
-- 2. Paste this whole file into the command bar and press Enter. Each asset is loaded with
--    InsertService:LoadAsset, measured, printed as one [HARVEST] line and destroyed.
-- 3. Right-click the Output window > Select All, then Ctrl+C.
-- 4. Run `py tools/assets/harvest.py` (reads the clipboard; or save the text and pass --file).
--
-- Per MeshPart it records the kit (node name), MeshId, TextureID (the Image asset), Size in studs
-- and Position relative to the inner model's pivot, which is the glTF origin (bottom-centre of
-- the footprint; docs/ASSET_RESEARCH.md section 3).
local ASSETS = {
%(entries)s
}

local InsertService = game:GetService("InsertService")
local HttpService = game:GetService("HttpService")

local function idFrom(content)
	return string.match(tostring(content), "%%d+") or "0"
end

local function round4(v)
	return math.round(v * 10000) / 10000
end

local function isIdentityRotation(cf)
	return (cf.RightVector - Vector3.xAxis).Magnitude < 1e-3
		and (cf.UpVector - Vector3.yAxis).Magnitude < 1e-3
		and (cf.LookVector + Vector3.zAxis).Magnitude < 1e-3
end

local loaded, failed = 0, 0
for _, asset in ASSETS do
	local ok, container = pcall(function()
		return InsertService:LoadAsset(asset.id)
	end)
	if not ok then
		print(
			string.format("[HARVEST-FAIL] %%s id %%d: %%s", asset.kind, asset.id, tostring(container))
		)
		failed += 1
		continue
	end
	-- LoadAsset wraps the upload in a container Model whose pivot is the bbox centre; the first
	-- Model inside is the uploaded file and its pivot is the glTF origin.
	local inner = container:FindFirstChildWhichIsA("Model")
	local pivot = if inner then inner:GetPivot() else container:GetPivot()
	local record = {
		kind = asset.kind,
		era = asset.era,
		model = asset.model,
		stage = asset.stage,
		kit = asset.kit,
		assetId = tostring(asset.id),
		parts = {},
	}
	for _, d in container:GetDescendants() do
		if d:IsA("MeshPart") then
			local offset = d.Position - pivot.Position
			table.insert(record.parts, {
				name = d.Name,
				parent = d.Parent and d.Parent.Name or "",
				meshId = idFrom(d.MeshId),
				imageId = idFrom(d.TextureID),
				size = { round4(d.Size.X), round4(d.Size.Y), round4(d.Size.Z) },
				offset = { round4(offset.X), round4(offset.Y), round4(offset.Z) },
				rotated = not isIdentityRotation(d.CFrame),
			})
		end
	end
	record.partCount = #record.parts
	print("[HARVEST] " .. HttpService:JSONEncode(record))
	container:Destroy()
	loaded += 1
end
print(
	string.format(
		"[HARVEST-DONE] %%d loaded, %%d failed - now copy the Output and run: py tools/assets/harvest.py",
		loaded,
		failed
	)
)
"""


def log(msg: str) -> None:
    print(f"[harvest] {msg}", flush=True)


def warn(msg: str) -> None:
    print(f"[harvest] WARNING: {msg}", flush=True)


def lua_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


# ---------------------------------------------------------------- emit


def emit(assets: dict, include_all: bool) -> int:
    lines = []
    for era, model, index, stage in cfg.iter_stages(assets):
        asset_id = int(stage.get("modelAssetId", 0))
        if asset_id == 0 or (not include_all and cfg.stage_harvested(stage)):
            continue
        lines.append(
            f"\t{{ kind = \"model\", era = {lua_string(era)}, model = {lua_string(model)}, stage = {index}, id = {asset_id} }},"
        )
    for kit in sorted(assets.get("textures", {})):
        tex = assets["textures"][kit]
        asset_id = int(tex.get("vipSwatchAssetId", 0))
        if asset_id == 0 or (not include_all and int(tex.get("vipImageId", 0)) != 0):
            continue
        lines.append(f"\t{{ kind = \"swatch\", kit = {lua_string(kit)}, id = {asset_id} }},")
    text = LUAU_TEMPLATE % {"entries": "\n".join(lines) if lines else "\t-- nothing to harvest"}
    with open(LUAU_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    log(f"wrote {os.path.relpath(LUAU_PATH, cfg.REPO_ROOT)} with {len(lines)} asset(s) to harvest")
    if not lines:
        log("nothing is waiting for harvest (upload first, or pass --all to re-harvest everything)")
    return 0


# ---------------------------------------------------------------- merge


def read_clipboard() -> str:
    try:
        result = subprocess.run(
            ["powershell", "-NoProfile", "-Command", "Get-Clipboard -Raw"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        warn(f"could not read the clipboard: {exc}")
        return ""
    return result.stdout or ""


def parse_records(text: str) -> list[dict]:
    records = []
    for raw in text.splitlines():
        pos = raw.find(MARKER)
        if pos < 0:
            continue
        body = raw[pos + len(MARKER) :].strip()
        # The Output window appends " - Edit"/" - Server" and similar after the message text.
        try:
            rec, _ = json.JSONDecoder().raw_decode(body)
        except ValueError:
            warn(f"unparseable line skipped: {body[:80]}...")
            continue
        if isinstance(rec, dict):
            records.append(rec)
    return records


def kit_of_part(part: dict, known: list[str]) -> str | None:
    """Roblox names the MeshPart after the mesh and its parent Model "<node>_Node"; both are the kit slug."""
    candidates = [str(part.get("name", "")), str(part.get("parent", ""))]
    for c in candidates:
        for suffix in ("_Node", ""):
            base = c[: -len(suffix)] if suffix and c.endswith(suffix) else c
            if base in known:
                return base
    if len(known) == 1:
        return known[0]
    return None


def merge_model(assets: dict, rec: dict, force: bool) -> bool:
    era, model = rec.get("era"), rec.get("model")
    try:
        stage_index = int(rec.get("stage"))
        entry = assets["eras"][era][model]
        stage = entry["stages"][stage_index]
    except (KeyError, TypeError, ValueError, IndexError):
        warn(f"no Assets.json entry for {era}/{model} stage {rec.get('stage')}; line skipped")
        return False
    label = f"{era}/{model} S{stage_index}"
    expected = int(stage.get("modelAssetId", 0))
    got = int(str(rec.get("assetId", "0")) or 0)
    if expected != got and not force:
        warn(f"{label}: printed asset {got} but Assets.json has {expected} (stale paste? use --force); skipped")
        return False
    parts_in = rec.get("parts") or []
    if not parts_in:
        warn(f"{label}: no MeshParts in the loaded asset; skipped")
        return False
    known = [p.get("kit") for p in stage.get("parts") or [] if p.get("kit")]
    merged: dict[str, dict] = {}
    for part in parts_in:
        kit = kit_of_part(part, known) or str(part.get("name") or "unknown")
        if kit not in known:
            warn(f"{label}: MeshPart {part.get('name')!r} matches no known kit {known}; recorded as {kit!r}")
        if kit in merged:
            warn(f"{label}: more than one MeshPart for kit {kit!r} (the merge should give one per kit); last wins")
        if part.get("rotated"):
            warn(f"{label}: {kit} MeshPart is rotated relative to the model; templates assume identity")
        merged[kit] = {
            "kit": kit,
            "meshId": int(str(part.get("meshId", "0")) or 0),
            "imageId": int(str(part.get("imageId", "0")) or 0),
            "size": [float(v) for v in part.get("size", [0, 0, 0])],
            "offset": [float(v) for v in part.get("offset", [0, 0, 0])],
        }
    stage["parts"] = [merged[k] for k in sorted(merged)]
    log(f"{label}: {len(merged)} part(s) " + ", ".join(f"{k} mesh {v['meshId']} image {v['imageId']}" for k, v in sorted(merged.items())))
    return True


def merge_swatch(assets: dict, rec: dict, force: bool) -> bool:
    kit = rec.get("kit")
    tex = assets.get("textures", {}).get(kit)
    if tex is None:
        warn(f"no textures entry for kit {kit!r}; line skipped")
        return False
    expected = int(tex.get("vipSwatchAssetId", 0))
    got = int(str(rec.get("assetId", "0")) or 0)
    if expected != got and not force:
        warn(f"VIP swatch {kit}: printed asset {got} but Assets.json has {expected}; skipped")
        return False
    parts = rec.get("parts") or []
    image_ids = [int(str(p.get("imageId", "0")) or 0) for p in parts]
    image_ids = [i for i in image_ids if i]
    if not image_ids:
        warn(f"VIP swatch {kit}: no TextureID on the loaded asset; skipped")
        return False
    tex["vipImageId"] = image_ids[0]
    log(f"VIP swatch {kit}: image {image_ids[0]}")
    return True


def list_missing(assets: dict) -> list[str]:
    missing = []
    for era, model, index, stage in cfg.iter_stages(assets):
        if int(stage.get("modelAssetId", 0)) != 0 and not cfg.stage_harvested(stage):
            missing.append(f"{era}/{model} S{index}")
    for kit in sorted(assets.get("textures", {})):
        tex = assets["textures"][kit]
        if int(tex.get("vipSwatchAssetId", 0)) != 0 and int(tex.get("vipImageId", 0)) == 0:
            missing.append(f"VIP swatch {kit}")
    return missing


def merge(assets: dict, text: str, force: bool) -> int:
    records = parse_records(text)
    if not records:
        warn("no [HARVEST] lines found (copy the whole Output window after running harvest.luau)")
        return 1
    models = swatches = 0
    for rec in records:
        kind = rec.get("kind")
        if kind == "model":
            models += merge_model(assets, rec, force)
        elif kind == "swatch":
            swatches += merge_swatch(assets, rec, force)
        else:
            warn(f"unknown record kind {kind!r}; skipped")
    cfg.save_assets(assets)
    log(f"merged {models} model stage(s) and {swatches} swatch(es) into {os.path.relpath(cfg.ASSETS_PATH, cfg.REPO_ROOT)}")
    missing = list_missing(assets)
    if missing:
        log("still missing harvest data: " + ", ".join(missing))
    else:
        log("every uploaded asset is harvested; next: py tools/assets/gen_templates.py")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--emit", action="store_true", help="write harvest.luau instead of merging")
    parser.add_argument("--all", action="store_true", help="with --emit: include already-harvested assets")
    parser.add_argument("--file", help="read Output text from this file instead of the clipboard")
    parser.add_argument("--force", action="store_true", help="merge lines whose asset id differs from Assets.json")
    args = parser.parse_args(argv)

    if not os.path.isfile(cfg.ASSETS_PATH):
        warn(f"{os.path.relpath(cfg.ASSETS_PATH, cfg.REPO_ROOT)} does not exist yet; run upload_models.py first")
        return 1
    assets = cfg.load_assets()
    if args.emit:
        return emit(assets, args.all)
    if args.file:
        with open(args.file, "r", encoding="utf-8", errors="replace") as fh:
            text = fh.read()
    else:
        text = read_clipboard()
    return merge(assets, text, args.force)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
