#!/usr/bin/env python
"""The one Studio step: generate the harvest snippet, then merge what Studio printed back.

    py tools/assets/harvest.py --emit [--all]     # write tools/assets/harvest.luau from Assets.json
    py tools/assets/harvest.py                    # merge [HARVEST] lines from the Windows clipboard
    py tools/assets/harvest.py --file out.txt     # ...or from a saved copy of the Output window
    py tools/assets/harvest.py --emit --props     # the same two steps for city-dressing props
    py tools/assets/harvest.py --props

Why a Studio step at all: Open Cloud returns one Model asset id per upload, but the template
files need the MeshId and TextureID (Image asset) that Roblox creates *inside* that model, plus
the MeshPart's size and its offset from the glTF origin. Only `InsertService:LoadAsset` in
Studio can reveal those. harvest.luau (generated, ids embedded, never edited by hand) loads
each asset, prints one `[HARVEST] {json}` line per asset and destroys what it loaded; this
script parses those lines and writes them into Assets.json. Missing lines leave entries
untouched and are listed.

--props works on Assets.json props.<Era>.<PropName> instead: the snippet tags each asset
kind "prop", and the merge step with --props takes only those lines (without it, only building
and swatch lines), so each paste lands exactly where its emit came from. --assets-json and
--luau redirect the files for dry runs.

Baked paths (Assets.json paths.<Era>, uploaded by upload_paths.py) ride along in both modes with
no flag of their own: a piece mesh with an assetId but no meshId is emitted as kind "pathPiece"
and a texture Decal with no imageId as kind "pathTexture", and either merge writes them back,
because paths belong to neither buildings nor props and should not wait on either paste. A
"pathTexture" line carrying a `variant` lands in paths.<Era>.variants.<name> instead of the era's
default pair (INTERFACES "Wave 1e - street upgrades").
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import assets_config as cfg  # noqa: E402

LUAU_PATH = os.path.join(HERE, "harvest.luau")
MARKER = "[HARVEST] "
MERGE_CMD = "py tools/assets/harvest.py"

LUAU_TEMPLATE = """\
-- Generated by `%(emit_cmd)s` from src/shared/Config/Assets.json. Do not edit.
--
-- 1. Open the place in Roblox Studio (Edit mode, not Play). View > Command Bar, View > Output.
-- 2. Paste this whole file into the command bar and press Enter. Each asset is loaded with
--    InsertService:LoadAsset, measured, printed as one [HARVEST] line and destroyed.
-- 3. Right-click the Output window > Select All, then Ctrl+C.
-- 4. Run `%(merge_cmd)s` (reads the clipboard; or save the text and pass --file).
--
-- Per MeshPart it records the kit (node name), MeshId, TextureID (the Image asset), Size in studs
-- and Position relative to the inner model's pivot, which is the glTF origin (bottom-centre of
-- the footprint; docs/ASSET_RESEARCH.md section 3).
local ASSETS = {
%(entries)s
}

local InsertService = game:GetService("InsertService")
local HttpService = game:GetService("HttpService")

local function idFrom(content)
	return string.match(tostring(content), "%%d+") or "0"
end

local function round4(v)
	return math.round(v * 10000) / 10000
end

local function isIdentityRotation(cf)
	return (cf.RightVector - Vector3.xAxis).Magnitude < 1e-3
		and (cf.UpVector - Vector3.yAxis).Magnitude < 1e-3
		and (cf.LookVector + Vector3.zAxis).Magnitude < 1e-3
end

local loaded, failed = 0, 0
for _, asset in ASSETS do
	local ok, container = pcall(function()
		return InsertService:LoadAsset(asset.id)
	end)
	if not ok then
		print(
			string.format("[HARVEST-FAIL] %%s id %%d: %%s", asset.kind, asset.id, tostring(container))
		)
		failed += 1
		continue
	end
	-- LoadAsset wraps the upload in a container Model whose pivot is the bbox centre; the first
	-- Model inside is the uploaded file and its pivot is the glTF origin.
	local inner = container:FindFirstChildWhichIsA("Model")
	local pivot = if inner then inner:GetPivot() else container:GetPivot()
	local record = {
		kind = asset.kind,
		era = asset.era,
		model = asset.model,
		stage = asset.stage,
		kit = asset.kit,
		piece = asset.piece,
		layer = asset.layer,
		variant = asset.variant,
		assetId = tostring(asset.id),
		parts = {},
	}
	for _, d in container:GetDescendants() do
		if asset.kind == "pathTexture" then
			-- A Decal upload loads as a Model holding one Decal; its Texture is the Image asset.
			if d:IsA("Decal") then
				record.imageId = idFrom(d.Texture)
			end
		elseif d:IsA("MeshPart") then
			local offset = d.Position - pivot.Position
			table.insert(record.parts, {
				name = d.Name,
				parent = d.Parent and d.Parent.Name or "",
				meshId = idFrom(d.MeshId),
				imageId = idFrom(d.TextureID),
				size = { round4(d.Size.X), round4(d.Size.Y), round4(d.Size.Z) },
				offset = { round4(offset.X), round4(offset.Y), round4(offset.Z) },
				rotated = not isIdentityRotation(d.CFrame),
			})
		end
	end
	record.partCount = #record.parts
	print("[HARVEST] " .. HttpService:JSONEncode(record))
	container:Destroy()
	loaded += 1
end
print(
	string.format(
		"[HARVEST-DONE] %%d loaded, %%d failed - now copy the Output and run: %(merge_cmd)s",
		loaded,
		failed
	)
)
"""


def log(msg: str) -> None:
    print(f"[harvest] {msg}", flush=True)


def warn(msg: str) -> None:
    print(f"[harvest] WARNING: {msg}", flush=True)


def lua_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


# ---------------------------------------------------------------- emit


def emit(assets: dict, include_all: bool, props: bool, luau_path: str) -> int:
    lines = []
    group, kind = ("props", "prop") if props else ("eras", "model")
    for era, model, index, stage in cfg.iter_stages(assets, group):
        asset_id = int(stage.get("modelAssetId", 0))
        if asset_id == 0 or (not include_all and cfg.stage_harvested(stage)):
            continue
        lines.append(
            f"\t{{ kind = \"{kind}\", era = {lua_string(era)}, model = {lua_string(model)}, stage = {index}, id = {asset_id} }},"
        )
    for kit in [] if props else sorted(assets.get("textures", {})):
        tex = assets["textures"][kit]
        asset_id = int(tex.get("vipSwatchAssetId", 0))
        if asset_id == 0 or (not include_all and int(tex.get("vipImageId", 0)) != 0):
            continue
        lines.append(f"\t{{ kind = \"swatch\", kit = {lua_string(kit)}, id = {asset_id} }},")
    for era, variant, layer, asset_id in pending_path_textures(assets, include_all):
        variant_field = f"variant = {lua_string(variant)}, " if variant else ""
        lines.append(
            f"\t{{ kind = \"pathTexture\", era = {lua_string(era)}, {variant_field}layer = {lua_string(layer)}, id = {asset_id} }},"
        )
    for era, piece_id, layer, asset_id in pending_path_pieces(assets, include_all):
        lines.append(
            f"\t{{ kind = \"pathPiece\", era = {lua_string(era)}, piece = {lua_string(piece_id)}, "
            f"layer = {lua_string(layer)}, id = {asset_id} }},"
        )
    flag = " --props" if props else ""
    text = LUAU_TEMPLATE % {
        "entries": "\n".join(lines) if lines else "\t-- nothing to harvest",
        "emit_cmd": f"{MERGE_CMD} --emit{flag}",
        "merge_cmd": MERGE_CMD + flag,
    }
    with open(luau_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    log(f"wrote {os.path.relpath(luau_path, cfg.REPO_ROOT)} with {len(lines)} asset(s) to harvest")
    if not lines:
        log("nothing is waiting for harvest (upload first, or pass --all to re-harvest everything)")
    return 0


def pending_path_textures(assets: dict, include_all: bool = False) -> list[tuple[str, str | None, str, int]]:
    """(era, variant or None, layer, assetId) for every uploaded path Decal whose Image asset is
    still unknown. Surface variants (INTERFACES "Wave 1e") ride along with the era's default pair,
    so one paste resolves every texture an era has."""
    out = []
    for era in sorted(assets.get(cfg.PATHS_KEY, {})):
        entry = assets[cfg.PATHS_KEY][era]
        variants = entry.get(cfg.PATH_VARIANTS_KEY) or {}
        for variant, block in [(None, entry)] + [(name, variants[name]) for name in sorted(variants)]:
            for layer in cfg.PATH_LAYERS:
                asset_id = int(block.get(f"{layer}AssetId", 0))
                if asset_id != 0 and (include_all or int(block.get(f"{layer}ImageId", 0)) == 0):
                    out.append((era, variant, layer, asset_id))
    return out


def pending_path_pieces(assets: dict, include_all: bool = False) -> list[tuple[str, str, str, int]]:
    out = []
    for era in sorted(assets.get(cfg.PATHS_KEY, {})):
        pieces = assets[cfg.PATHS_KEY][era].get("pieces") or {}
        for piece_id in sorted(pieces):
            for layer in cfg.PATH_LAYERS:
                mesh = pieces[piece_id].get(layer) or {}
                asset_id = int(mesh.get("assetId", 0))
                if asset_id != 0 and (include_all or int(mesh.get("meshId", 0)) == 0):
                    out.append((era, piece_id, layer, asset_id))
    return out


# ---------------------------------------------------------------- merge


def read_clipboard() -> str:
    try:
        result = subprocess.run(
            ["powershell", "-NoProfile", "-Command", "Get-Clipboard -Raw"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        warn(f"could not read the clipboard: {exc}")
        return ""
    return result.stdout or ""


def parse_records(text: str) -> list[dict]:
    records = []
    for raw in text.splitlines():
        pos = raw.find(MARKER)
        if pos < 0:
            continue
        body = raw[pos + len(MARKER) :].strip()
        # The Output window appends " - Edit"/" - Server" and similar after the message text.
        try:
            rec, _ = json.JSONDecoder().raw_decode(body)
        except ValueError:
            warn(f"unparseable line skipped: {body[:80]}...")
            continue
        if isinstance(rec, dict):
            records.append(rec)
    return records


def kit_of_part(part: dict, known: list[str]) -> str | None:
    """Roblox names the MeshPart after the mesh and its parent Model "<node>_Node"; both are the kit slug."""
    candidates = [str(part.get("name", "")), str(part.get("parent", ""))]
    for c in candidates:
        for suffix in ("_Node", ""):
            base = c[: -len(suffix)] if suffix and c.endswith(suffix) else c
            if base in known:
                return base
    if len(known) == 1:
        return known[0]
    return None


def merge_model(assets: dict, rec: dict, force: bool, group: str = "eras") -> bool:
    era, model = rec.get("era"), rec.get("model")
    prefix = "" if group == "eras" else f"{group}/"
    try:
        stage_index = int(rec.get("stage"))
        entry = assets[group][era][model]
        stage = entry["stages"][stage_index]
    except (KeyError, TypeError, ValueError, IndexError):
        warn(f"no Assets.json entry for {prefix}{era}/{model} stage {rec.get('stage')}; line skipped")
        return False
    label = f"{prefix}{era}/{model} S{stage_index}"
    expected = int(stage.get("modelAssetId", 0))
    got = int(str(rec.get("assetId", "0")) or 0)
    if expected != got and not force:
        warn(f"{label}: printed asset {got} but Assets.json has {expected} (stale paste? use --force); skipped")
        return False
    parts_in = rec.get("parts") or []
    if not parts_in:
        warn(f"{label}: no MeshParts in the loaded asset; skipped")
        return False
    known = [p.get("kit") for p in stage.get("parts") or [] if p.get("kit")]
    merged: dict[str, dict] = {}
    for part in parts_in:
        kit = kit_of_part(part, known) or str(part.get("name") or "unknown")
        if kit not in known:
            warn(f"{label}: MeshPart {part.get('name')!r} matches no known kit {known}; recorded as {kit!r}")
        if kit in merged:
            warn(f"{label}: more than one MeshPart for kit {kit!r} (the merge should give one per kit); last wins")
        if part.get("rotated"):
            warn(f"{label}: {kit} MeshPart is rotated relative to the model; templates assume identity")
        merged[kit] = {
            "kit": kit,
            "meshId": int(str(part.get("meshId", "0")) or 0),
            "imageId": int(str(part.get("imageId", "0")) or 0),
            "size": [float(v) for v in part.get("size", [0, 0, 0])],
            "offset": [float(v) for v in part.get("offset", [0, 0, 0])],
        }
    stage["parts"] = [merged[k] for k in sorted(merged)]
    log(f"{label}: {len(merged)} part(s) " + ", ".join(f"{k} mesh {v['meshId']} image {v['imageId']}" for k, v in sorted(merged.items())))
    return True


def merge_swatch(assets: dict, rec: dict, force: bool) -> bool:
    kit = rec.get("kit")
    tex = assets.get("textures", {}).get(kit)
    if tex is None:
        warn(f"no textures entry for kit {kit!r}; line skipped")
        return False
    expected = int(tex.get("vipSwatchAssetId", 0))
    got = int(str(rec.get("assetId", "0")) or 0)
    if expected != got and not force:
        warn(f"VIP swatch {kit}: printed asset {got} but Assets.json has {expected}; skipped")
        return False
    parts = rec.get("parts") or []
    image_ids = [int(str(p.get("imageId", "0")) or 0) for p in parts]
    image_ids = [i for i in image_ids if i]
    if not image_ids:
        warn(f"VIP swatch {kit}: no TextureID on the loaded asset; skipped")
        return False
    tex["vipImageId"] = image_ids[0]
    log(f"VIP swatch {kit}: image {image_ids[0]}")
    return True


def merge_path_texture(assets: dict, rec: dict, force: bool) -> bool:
    era, layer, variant = rec.get("era"), rec.get("layer"), rec.get("variant")
    entry = assets.get(cfg.PATHS_KEY, {}).get(era)
    if entry is not None and variant:
        entry = (entry.get(cfg.PATH_VARIANTS_KEY) or {}).get(variant)
    if entry is None or layer not in cfg.PATH_LAYERS:
        warn(f"no paths entry for era {era!r}{f' variant {variant!r}' if variant else ''} layer {layer!r}; line skipped")
        return False
    label = f"path texture {era} {variant + ' ' if variant else ''}{layer}"
    expected = int(entry.get(f"{layer}AssetId", 0))
    got = int(str(rec.get("assetId", "0")) or 0)
    if expected != got and not force:
        warn(f"{label}: printed asset {got} but Assets.json has {expected}; skipped")
        return False
    image_id = int(str(rec.get("imageId", "0")) or 0)
    if image_id == 0:
        warn(f"{label}: no Decal Texture on the loaded asset (still in moderation?); skipped")
        return False
    entry[f"{layer}ImageId"] = image_id
    log(f"{label}: image {image_id}")
    return True


def merge_path_piece(assets: dict, rec: dict, force: bool) -> bool:
    """One piece mesh: the MeshId, Size and offset from the glTF origin of the single MeshPart
    Roblox built inside the uploaded Model. The offset comes back sign-negated in x and z, because
    the importer turns the geometry 180 deg about Y; it is recorded exactly as Studio reported it
    and gen_templates.py applies the turn."""
    era, piece_id, layer = rec.get("era"), rec.get("piece"), rec.get("layer")
    pieces = (assets.get(cfg.PATHS_KEY, {}).get(era) or {}).get("pieces") or {}
    mesh = (pieces.get(piece_id) or {}).get(layer) if layer in cfg.PATH_LAYERS else None
    if mesh is None:
        warn(f"no paths entry for {era}/{piece_id}/{layer}; line skipped")
        return False
    label = f"path {era} {piece_id} {layer}"
    expected = int(mesh.get("assetId", 0))
    got = int(str(rec.get("assetId", "0")) or 0)
    if expected != got and not force:
        warn(f"{label}: printed asset {got} but Assets.json has {expected} (stale paste? use --force); skipped")
        return False
    parts = rec.get("parts") or []
    if len(parts) != 1:
        warn(f"{label}: expected exactly one MeshPart, got {len(parts)}; skipped")
        return False
    part = parts[0]
    mesh_id = int(str(part.get("meshId", "0")) or 0)
    if mesh_id == 0:
        warn(f"{label}: MeshPart has no MeshId; skipped")
        return False
    if part.get("rotated"):
        warn(f"{label}: MeshPart is rotated relative to the model beyond the importer's 180 deg turn")
    mesh.update(
        {
            "meshId": mesh_id,
            "size": [float(v) for v in part.get("size", [0, 0, 0])],
            "offset": [float(v) for v in part.get("offset", [0, 0, 0])],
        }
    )
    return True


def list_missing(assets: dict, props: bool) -> list[str]:
    missing = []
    group, prefix = ("props", "props/") if props else ("eras", "")
    for era, model, index, stage in cfg.iter_stages(assets, group):
        if int(stage.get("modelAssetId", 0)) != 0 and not cfg.stage_harvested(stage):
            missing.append(f"{prefix}{era}/{model} S{index}")
    for kit in [] if props else sorted(assets.get("textures", {})):
        tex = assets["textures"][kit]
        if int(tex.get("vipSwatchAssetId", 0)) != 0 and int(tex.get("vipImageId", 0)) == 0:
            missing.append(f"VIP swatch {kit}")
    missing += [
        f"path texture {era} {variant + ' ' if variant else ''}{layer}"
        for era, variant, layer, _ in pending_path_textures(assets)
    ]
    pieces = pending_path_pieces(assets)
    if pieces:
        missing.append(f"{len(pieces)} path piece mesh(es)")
    return missing


def merge(assets: dict, text: str, force: bool, props: bool) -> int:
    records = parse_records(text)
    if not records:
        warn("no [HARVEST] lines found (copy the whole Output window after running harvest.luau)")
        return 1
    models = swatches = path_textures = path_pieces = 0
    for rec in records:
        kind = rec.get("kind")
        if kind == "pathTexture":
            path_textures += merge_path_texture(assets, rec, force)
        elif kind == "pathPiece":
            path_pieces += merge_path_piece(assets, rec, force)
        elif props:
            if kind == "prop":
                models += merge_model(assets, rec, force, "props")
            else:
                warn(f"{kind!r} line skipped (--props merges only prop lines; rerun without --props for it)")
        elif kind == "model":
            models += merge_model(assets, rec, force)
        elif kind == "swatch":
            swatches += merge_swatch(assets, rec, force)
        elif kind == "prop":
            warn("prop line skipped (rerun with --props to merge it)")
        else:
            warn(f"unknown record kind {kind!r}; skipped")
    cfg.save_assets(assets)
    if props:
        log(f"merged {models} prop stage(s) into {os.path.relpath(cfg.ASSETS_PATH, cfg.REPO_ROOT)}")
    else:
        log(f"merged {models} model stage(s) and {swatches} swatch(es) into {os.path.relpath(cfg.ASSETS_PATH, cfg.REPO_ROOT)}")
    if path_textures or path_pieces:
        log(f"merged {path_textures} path texture(s) and {path_pieces} path piece mesh(es)")
    missing = list_missing(assets, props)
    if missing:
        log("still missing harvest data: " + ", ".join(missing))
    else:
        commands = ["py tools/assets/gen_templates.py" + (" --props" if props else "")]
        if path_textures or path_pieces:
            commands.append("py tools/assets/gen_templates.py --paths")
        log("every uploaded asset is harvested; next: " + ", then ".join(commands))
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--emit", action="store_true", help="write harvest.luau instead of merging")
    parser.add_argument("--all", action="store_true", help="with --emit: include already-harvested assets")
    parser.add_argument("--file", help="read Output text from this file instead of the clipboard")
    parser.add_argument("--force", action="store_true", help="merge lines whose asset id differs from Assets.json")
    parser.add_argument("--props", action="store_true", help="emit / merge city-dressing props instead of buildings")
    parser.add_argument("--assets-json", help="read and write this Assets.json instead of src/shared/Config/Assets.json")
    parser.add_argument("--luau", help="with --emit: write the snippet here instead of tools/assets/harvest.luau")
    args = parser.parse_args(argv)
    cfg.use_assets_path(args.assets_json)

    if not os.path.isfile(cfg.ASSETS_PATH):
        warn(f"{os.path.relpath(cfg.ASSETS_PATH, cfg.REPO_ROOT)} does not exist yet; run upload_models.py first")
        return 1
    assets = cfg.load_assets()
    if args.emit:
        return emit(assets, args.all, args.props, os.path.abspath(args.luau) if args.luau else LUAU_PATH)
    if args.file:
        with open(args.file, "r", encoding="utf-8", errors="replace") as fh:
            text = fh.read()
    else:
        text = read_clipboard()
    return merge(assets, text, args.force, args.props)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
