#!/usr/bin/env python
"""The one Studio step of the path look test: emit the harvest snippet, then read back its Output.

    py tools/pathtest/harvest_pathtest.py --emit            # write harvest_pathtest.luau from pathtest_assets.json
    py tools/pathtest/harvest_pathtest.py --file out.txt    # merge [PATHTEST] lines from a saved Output copy
    py tools/pathtest/harvest_pathtest.py                   # ...or straight from the Windows clipboard

Open Cloud returns only the Model / Decal asset ids. The MeshId and Size of the MeshPart Roblox
builds inside each model, and the Image asset inside each Decal, can only be read in Studio with
InsertService:LoadAsset, exactly like tools/assets/harvest.py does for buildings. The snippet
prints one `[PATHTEST] {json}` line per asset and a `[PATHTEST-DONE]` line; this script writes
meshId/size/offset and imageId into pathtest_assets.json. A line whose asset id no longer matches
the JSON (a re-upload happened after the paste) is skipped.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS_JSON = os.path.join(HERE, "pathtest_assets.json")
LUAU_PATH = os.path.join(HERE, "harvest_pathtest.luau")
MARKER = "[PATHTEST] "
DONE_MARKER = "[PATHTEST-DONE]"

LUAU_TEMPLATE = """\
-- Generated by `py tools/pathtest/harvest_pathtest.py --emit`
-- from tools/pathtest/pathtest_assets.json. Do not edit.
--
-- 1. Roblox Studio, Edit mode (not Play). View > Command Bar and View > Output.
-- 2. Paste this whole file into the command bar and press Enter.
-- 3. Right-click the Output window > Select All, Ctrl+C, and hand the text to the lead, who runs
--    `py tools/pathtest/harvest_pathtest.py --file <saved output>`.
local ASSETS = {
%(entries)s
}

local InsertService = game:GetService("InsertService")
local HttpService = game:GetService("HttpService")

local function idFrom(content)
	return string.match(tostring(content), "%%d+") or "0"
end

local function round4(v)
	return math.round(v * 10000) / 10000
end

local loaded, failed = 0, 0
for _, asset in ASSETS do
	local ok, container = pcall(function()
		return InsertService:LoadAsset(asset.id)
	end)
	if not ok then
		print(
			string.format("[PATHTEST-FAIL] %%s id %%d: %%s", asset.name, asset.id, tostring(container))
		)
		failed += 1
		continue
	end
	local record =
		{ kind = asset.kind, name = asset.name, assetId = tostring(asset.id), parts = {} }
	-- The first Model in the LoadAsset container is the uploaded file; its pivot is the glTF origin.
	local inner = container:FindFirstChildWhichIsA("Model")
	local pivot = if inner then inner:GetPivot() else container:GetPivot()
	for _, d in container:GetDescendants() do
		if d:IsA("Decal") then
			record.imageId = idFrom(d.Texture)
		elseif d:IsA("MeshPart") then
			local offset = d.Position - pivot.Position
			table.insert(record.parts, {
				meshId = idFrom(d.MeshId),
				size = { round4(d.Size.X), round4(d.Size.Y), round4(d.Size.Z) },
				offset = { round4(offset.X), round4(offset.Y), round4(offset.Z) },
			})
		end
	end
	print("[PATHTEST] " .. HttpService:JSONEncode(record))
	container:Destroy()
	loaded += 1
end
print(
	string.format(
		"[PATHTEST-DONE] %%d loaded, %%d failed - copy the whole Output for the lead",
		loaded,
		failed
	)
)
"""


def log(msg: str) -> None:
    print(f"[pathtest] {msg}", flush=True)


def load() -> dict:
    if not os.path.isfile(ASSETS_JSON):
        raise SystemExit("pathtest_assets.json does not exist; run py tools/pathtest/upload.py first")
    with open(ASSETS_JSON, encoding="utf-8") as fh:
        return json.load(fh)


def save(data: dict) -> None:
    tmp = ASSETS_JSON + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(data, fh, indent=2)
        fh.write("\n")
    os.replace(tmp, ASSETS_JSON)


def emit(data: dict, include_all: bool = False) -> int:
    lines = []
    for group, kind in (("models", "model"), ("images", "image")):
        harvested_key = "meshId" if group == "models" else "imageId"
        for name, entry in data[group].items():
            if int(entry["assetId"]) == 0:
                log(f"{name}: not uploaded yet; left out of the snippet")
                continue
            if not include_all and int(entry.get(harvested_key) or 0) != 0:
                continue  # already harvested; Ben only needs to load what is new
            lines.append(f'\t{{ kind = "{kind}", name = "{name}", id = {int(entry["assetId"])} }},')
    with open(LUAU_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(LUAU_TEMPLATE % {"entries": "\n".join(lines)})
    log(f"wrote {os.path.relpath(LUAU_PATH)} with {len(lines)} asset(s) to harvest")
    if not lines:
        log("nothing is waiting for harvest (upload first, or pass --all to re-harvest everything)")
    return 0


def read_clipboard() -> str:
    try:
        result = subprocess.run(
            ["powershell", "-NoProfile", "-Command", "Get-Clipboard -Raw"],
            capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        log(f"could not read the clipboard: {exc}")
        return ""
    return result.stdout or ""


def parse(text: str) -> tuple[list[dict], bool]:
    records = []
    for raw in text.splitlines():
        pos = raw.find(MARKER)
        if pos < 0:
            continue
        try:
            rec, _ = json.JSONDecoder().raw_decode(raw[pos + len(MARKER) :].strip())
        except ValueError:
            log(f"unparseable line skipped: {raw[:80]}")
            continue
        if isinstance(rec, dict):
            records.append(rec)
    return records, DONE_MARKER in text


def merge(data: dict, text: str) -> int:
    records, done = parse(text)
    if not records:
        log("no [PATHTEST] lines found (copy the whole Output window after running the snippet)")
        return 1
    if not done:
        log("WARNING: no [PATHTEST-DONE] line; the paste may be cut short")
    merged = 0
    for rec in records:
        group = "models" if rec.get("kind") == "model" else "images"
        entry = data[group].get(rec.get("name"))
        if entry is None:
            log(f"unknown asset {rec.get('name')!r}; skipped")
            continue
        if str(entry["assetId"]) != str(rec.get("assetId")):
            log(f"{rec['name']}: printed asset {rec.get('assetId')} but the JSON has {entry['assetId']} (stale paste); skipped")
            continue
        if group == "models":
            parts = rec.get("parts") or []
            if len(parts) != 1:
                log(f"{rec['name']}: expected exactly one MeshPart, got {len(parts)}; skipped")
                continue
            part = parts[0]
            mesh_id = int(str(part.get("meshId", "0")) or 0)
            if mesh_id == 0:
                log(f"{rec['name']}: MeshPart has no MeshId; skipped")
                continue
            entry.update({"meshId": mesh_id, "size": [float(v) for v in part["size"]], "offset": [float(v) for v in part["offset"]]})
            log(f"{rec['name']}: mesh {mesh_id} size {entry['size']} offset {entry['offset']}")
        else:
            image_id = int(str(rec.get("imageId", "0")) or 0)
            if image_id == 0:
                log(f"{rec['name']}: no Decal texture in the loaded asset (still in moderation?); skipped")
                continue
            entry["imageId"] = image_id
            log(f"{rec['name']}: image {image_id}")
        merged += 1
    save(data)
    missing = [n for n, e in data["models"].items() if not e.get("meshId")] + [n for n, e in data["images"].items() if not e.get("imageId")]
    log(f"merged {merged} line(s)" + (f"; still missing: {', '.join(missing)}" if missing else "; all harvested, next: py tools/pathtest/gen_display.py"))
    return 0 if not missing else 1


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--emit", action="store_true", help="write harvest_pathtest.luau")
    parser.add_argument("--all", action="store_true", help="with --emit: include already-harvested assets")
    parser.add_argument("--file", help="read the Studio Output from this file instead of the clipboard")
    parser.add_argument("--assets-json", help="use this ids JSON instead of tools/pathtest/pathtest_assets.json (tests)")
    args = parser.parse_args(argv)
    global ASSETS_JSON
    if args.assets_json:
        ASSETS_JSON = os.path.abspath(args.assets_json)
    data = load()
    if args.emit:
        return emit(data, args.all)
    if args.file:
        with open(args.file, encoding="utf-8", errors="replace") as fh:
            text = fh.read()
    else:
        text = read_clipboard()
    return merge(data, text)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
