#!/usr/bin/env python
"""Asset manifest generator for Era City Tycoon (spec section 8).

Reads every era config in src/shared/Config/Eras/*.json (the same repo-root
relative path tools/sim_economy.py uses) and writes docs/ASSET_MANIFEST.md:
one section per era in eraIndex order, the kits that era draws from, and a
purchase-order table of every modelName the human must import. Output is
deterministic (stable ordering, no timestamps) so --check can diff it.

Usage:
  py tools/gen_asset_manifest.py           # (re)write docs/ASSET_MANIFEST.md
  py tools/gen_asset_manifest.py --check   # validate configs + compare the
                                           # committed manifest; exit 1 and
                                           # print one line per problem
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ERAS_DIR = REPO_ROOT / "src" / "shared" / "Config" / "Eras"
MANIFEST_PATH = REPO_ROOT / "docs" / "ASSET_MANIFEST.md"

# Era config schema v1.1 (INTERFACES.md): modelName must be PascalCase.
MODEL_NAME_RE = re.compile(r"^[A-Z][A-Za-z0-9]*$")
REQUIRED_SLOT_FIELDS = ("modelName", "description", "kit")


def load_eras() -> list[dict]:
    eras = []
    for path in sorted(ERAS_DIR.glob("*.json")):
        with open(path, encoding="utf-8") as handle:
            era = json.load(handle)
        era["_file"] = path.name
        eras.append(era)
    eras.sort(key=lambda era: era.get("eraIndex", 0))
    return eras


def validate(eras: list[dict]) -> list[str]:
    """Return one human-readable line per schema problem (empty = clean)."""
    problems: list[str] = []
    for era in eras:
        label = era["_file"]
        if not str(era.get("displayName", "")).strip():
            problems.append(f"{label}: missing displayName")
        seen: dict[str, str] = {}
        for index, slot in enumerate(era.get("slots", []), start=1):
            slot_label = f"{label} slot #{index} ({slot.get('id', '?')})"
            for field in REQUIRED_SLOT_FIELDS:
                if not str(slot.get(field, "")).strip():
                    problems.append(f"{slot_label}: missing or empty {field}")
            model = slot.get("modelName")
            if not model:
                continue
            if not MODEL_NAME_RE.match(model):
                problems.append(f"{slot_label}: modelName '{model}' is not PascalCase")
            if model in seen:
                problems.append(
                    f"{slot_label}: duplicate modelName '{model}' (also slot {seen[model]})"
                )
            seen.setdefault(model, slot.get("id", "?"))
    return problems


def md_cell(text: object) -> str:
    return str(text).replace("|", r"\|").replace("\n", " ")


def render(eras: list[dict]) -> str:
    lines: list[str] = [
        "# Asset manifest",
        "",
        "Generated by `py tools/gen_asset_manifest.py` from `src/shared/Config/Eras/*.json`.",
        "Do not edit by hand -- rerun the script; `py tools/gen_asset_manifest.py --check`",
        "fails when this file is stale.",
        "",
        "## Naming rule",
        "",
        "- Every imported model is a `Model` placed at `ServerStorage/Assets/<name>/<modelName>`,",
        "  where `<name>` is the era's config `name` (the folder key, e.g. `OrbitalColony`) and",
        "  `<modelName>` must equal the config `modelName` **exactly** (PascalCase, no spaces).",
        "- VIP variants (recolored or alternate models) go in `ServerStorage/Assets/<name>_VIP/`",
        "  under the same `<modelName>`. A missing VIP variant falls back to the normal model; a",
        "  missing normal model falls back to a placeholder part -- never an error.",
        "- Import rules (scale, PrimaryPart, anchoring, colormap) live in `docs/MANUAL_STEPS.md`.",
        "- Tick the last column once the model is imported and named correctly.",
        "",
    ]
    for era in eras:
        display = era.get("displayName") or era.get("name", "?")
        name = era.get("name", "?")
        slots = era.get("slots", [])
        kits = sorted({slot.get("kit", "") for slot in slots if slot.get("kit")})
        lines += [
            f"## Era {era.get('eraIndex', '?')} — {display}",
            "",
            f"Folder: `ServerStorage/Assets/{name}/` (VIP: `ServerStorage/Assets/{name}_VIP/`)",
            "",
            "Kits: " + (", ".join(kits) if kits else "(none listed)"),
            "",
            "| # | modelName | Slot | Type | Kit | Description | Imported |",
            "|---|-----------|------|------|-----|-------------|----------|",
        ]
        for index, slot in enumerate(slots, start=1):
            lines.append(
                "| {} | `{}` | {} | {} | {} | {} | [ ] |".format(
                    index,
                    md_cell(slot.get("modelName", "")),
                    md_cell(slot.get("name", "")),
                    md_cell(slot.get("type", "")),
                    md_cell(slot.get("kit", "")),
                    md_cell(slot.get("description", "")),
                )
            )
        lines.append("")
    per_era = ", ".join(
        f"Era {era.get('eraIndex', '?')}: {len(era.get('slots', []))}" for era in eras
    )
    total = sum(len(era.get("slots", [])) for era in eras)
    lines += ["## Totals", "", f"{total} models ({per_era})", ""]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Generate docs/ASSET_MANIFEST.md from the era configs.",
        epilog="Run from anywhere; paths resolve relative to the repo root.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate the era configs and fail if the committed manifest is stale",
    )
    args = parser.parse_args(argv)

    eras = load_eras()
    if not eras:
        print(f"no era configs found in {ERAS_DIR}")
        return 1
    text = render(eras)

    if args.check:
        problems = validate(eras)
        if MANIFEST_PATH.exists():
            committed = MANIFEST_PATH.read_text(encoding="utf-8")
            if committed != text:
                problems.append(
                    f"{MANIFEST_PATH.relative_to(REPO_ROOT)} is stale -- "
                    "rerun py tools/gen_asset_manifest.py"
                )
        else:
            problems.append(f"{MANIFEST_PATH.relative_to(REPO_ROOT)} is missing")
        for line in problems:
            print(line)
        if problems:
            print(f"CHECK: FAIL -- {len(problems)} problem(s)")
            return 1
        print("CHECK: PASS -- configs valid, manifest up to date")
        return 0

    with open(MANIFEST_PATH, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    total = sum(len(era.get("slots", [])) for era in eras)
    print(f"wrote {MANIFEST_PATH.relative_to(REPO_ROOT)}: {len(eras)} eras, {total} models")
    problems = validate(eras)
    for line in problems:
        print("warning:", line)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
